server:
  port: 8090

spring:
#  rabbitmq:
#    host: localhost
#    port: 15672
#    username: guest
#    password: guest
#    main:
#      allow-bean-definition-overriding: true
  #  application:
  #    name: wekaclassificationalgorithmprovider
  #  eureka:
  #    client:
  #      serviceUrl:
  #        defaultZone: http://localhost:8761/eureka/
    cloud:
      stream:
        function:
          definition: modelRequestConsumer
        bindings:
             modelRequestConsumer-in-0:
                destination: wekaTopic


defaultTopic:
  topic: manager_in
wekaTopic:
  topic: weka-provider_in
customErrorTopic:
  topic: error-message

